/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PublicAuthRouteImport } from './routes/_public/_auth'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicAuctionsRouteImport } from './routes/_public/auctions'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicPoliciesRouteImport } from './routes/_public/policies'
import { Route as PublicSafetyRouteImport } from './routes/_public/safety'
import { Route as DashboardAuctionsRouteImport } from './routes/dashboard/auctions'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard/bookmarks'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardMyAuctionsRouteImport } from './routes/dashboard/my-auctions'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPayoutsRouteImport } from './routes/dashboard/payouts'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/_auth/login'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/_auth/register'
import { Route as PublicAuthResetPasswordRouteImport } from './routes/_public/_auth/reset-password'
import { Route as PublicAuctionsIdRouteImport } from './routes/_public/auctions.$id'
import { Route as DashboardMyAuctionsIdRouteImport } from './routes/dashboard/my-auctions.$id'
import { Route as DashboardMyAuctionsNewRouteImport } from './routes/dashboard/my-auctions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuctionsRoute = PublicAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliciesRoute = PublicPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSafetyRoute = PublicSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardAuctionsRoute = DashboardAuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyAuctionsRoute = DashboardMyAuctionsRouteImport.update({
  id: '/my-auctions',
  path: '/my-auctions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPayoutsRoute = DashboardPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSetupRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuthResetPasswordRoute = PublicAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicAuthRoute,
} as any)
const PublicAuctionsIdRoute = PublicAuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicAuctionsRoute,
} as any)
const DashboardMyAuctionsIdRoute = DashboardMyAuctionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardMyAuctionsRoute,
} as any)
const DashboardMyAuctionsNewRoute = DashboardMyAuctionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMyAuctionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/auctions': typeof PublicAuctionsRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/policies': typeof PublicPoliciesRoute
  '/safety': typeof PublicSafetyRoute
  '/dashboard/auctions': typeof DashboardAuctionsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/reset-password': typeof PublicAuthResetPasswordRoute
  '/auctions/$id': typeof PublicAuctionsIdRoute
  '/dashboard/my-auctions/$id': typeof DashboardMyAuctionsIdRoute
  '/dashboard/my-auctions/new': typeof DashboardMyAuctionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/auctions': typeof PublicAuctionsRouteWithChildren
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/policies': typeof PublicPoliciesRoute
  '/safety': typeof PublicSafetyRoute
  '/dashboard/auctions': typeof DashboardAuctionsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/login': typeof PublicAuthLoginRoute
  '/register': typeof PublicAuthRegisterRoute
  '/reset-password': typeof PublicAuthResetPasswordRoute
  '/auctions/$id': typeof PublicAuctionsIdRoute
  '/dashboard/my-auctions/$id': typeof DashboardMyAuctionsIdRoute
  '/dashboard/my-auctions/new': typeof DashboardMyAuctionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/_auth': typeof PublicAuthRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/auctions': typeof PublicAuctionsRouteWithChildren
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/policies': typeof PublicPoliciesRoute
  '/_public/safety': typeof PublicSafetyRoute
  '/dashboard/auctions': typeof DashboardAuctionsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRouteWithChildren
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payouts': typeof DashboardPayoutsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/setup': typeof DashboardSetupRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/_public/_auth/login': typeof PublicAuthLoginRoute
  '/_public/_auth/register': typeof PublicAuthRegisterRoute
  '/_public/_auth/reset-password': typeof PublicAuthResetPasswordRoute
  '/_public/auctions/$id': typeof PublicAuctionsIdRoute
  '/dashboard/my-auctions/$id': typeof DashboardMyAuctionsIdRoute
  '/dashboard/my-auctions/new': typeof DashboardMyAuctionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/auctions'
    | '/contact'
    | '/faq'
    | '/policies'
    | '/safety'
    | '/dashboard/auctions'
    | '/dashboard/bookmarks'
    | '/dashboard/home'
    | '/dashboard/my-auctions'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auctions/$id'
    | '/dashboard/my-auctions/$id'
    | '/dashboard/my-auctions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/auctions'
    | '/contact'
    | '/faq'
    | '/policies'
    | '/safety'
    | '/dashboard/auctions'
    | '/dashboard/bookmarks'
    | '/dashboard/home'
    | '/dashboard/my-auctions'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auctions/$id'
    | '/dashboard/my-auctions/$id'
    | '/dashboard/my-auctions/new'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/dashboard'
    | '/_public/_auth'
    | '/_public/about'
    | '/_public/auctions'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/policies'
    | '/_public/safety'
    | '/dashboard/auctions'
    | '/dashboard/bookmarks'
    | '/dashboard/home'
    | '/dashboard/my-auctions'
    | '/dashboard/orders'
    | '/dashboard/payouts'
    | '/dashboard/profile'
    | '/dashboard/setup'
    | '/dashboard/users'
    | '/_public/_auth/login'
    | '/_public/_auth/register'
    | '/_public/_auth/reset-password'
    | '/_public/auctions/$id'
    | '/dashboard/my-auctions/$id'
    | '/dashboard/my-auctions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_auth': {
      id: '/_public/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auctions': {
      id: '/_public/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof PublicAuctionsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/policies': {
      id: '/_public/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PublicPoliciesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/safety': {
      id: '/_public/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof PublicSafetyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/auctions': {
      id: '/dashboard/auctions'
      path: '/auctions'
      fullPath: '/dashboard/auctions'
      preLoaderRoute: typeof DashboardAuctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-auctions': {
      id: '/dashboard/my-auctions'
      path: '/my-auctions'
      fullPath: '/dashboard/my-auctions'
      preLoaderRoute: typeof DashboardMyAuctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payouts': {
      id: '/dashboard/payouts'
      path: '/payouts'
      fullPath: '/dashboard/payouts'
      preLoaderRoute: typeof DashboardPayoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/_auth/login': {
      id: '/_public/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/register': {
      id: '/_public/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/_auth/reset-password': {
      id: '/_public/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicAuthResetPasswordRouteImport
      parentRoute: typeof PublicAuthRoute
    }
    '/_public/auctions/$id': {
      id: '/_public/auctions/$id'
      path: '/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof PublicAuctionsIdRouteImport
      parentRoute: typeof PublicAuctionsRoute
    }
    '/dashboard/my-auctions/$id': {
      id: '/dashboard/my-auctions/$id'
      path: '/$id'
      fullPath: '/dashboard/my-auctions/$id'
      preLoaderRoute: typeof DashboardMyAuctionsIdRouteImport
      parentRoute: typeof DashboardMyAuctionsRoute
    }
    '/dashboard/my-auctions/new': {
      id: '/dashboard/my-auctions/new'
      path: '/new'
      fullPath: '/dashboard/my-auctions/new'
      preLoaderRoute: typeof DashboardMyAuctionsNewRouteImport
      parentRoute: typeof DashboardMyAuctionsRoute
    }
  }
}

interface PublicAuthRouteChildren {
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicAuthResetPasswordRoute: typeof PublicAuthResetPasswordRoute
}

const PublicAuthRouteChildren: PublicAuthRouteChildren = {
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicAuthResetPasswordRoute: PublicAuthResetPasswordRoute,
}

const PublicAuthRouteWithChildren = PublicAuthRoute._addFileChildren(
  PublicAuthRouteChildren,
)

interface PublicAuctionsRouteChildren {
  PublicAuctionsIdRoute: typeof PublicAuctionsIdRoute
}

const PublicAuctionsRouteChildren: PublicAuctionsRouteChildren = {
  PublicAuctionsIdRoute: PublicAuctionsIdRoute,
}

const PublicAuctionsRouteWithChildren = PublicAuctionsRoute._addFileChildren(
  PublicAuctionsRouteChildren,
)

interface PublicRouteChildren {
  PublicAuthRoute: typeof PublicAuthRouteWithChildren
  PublicAboutRoute: typeof PublicAboutRoute
  PublicAuctionsRoute: typeof PublicAuctionsRouteWithChildren
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicPoliciesRoute: typeof PublicPoliciesRoute
  PublicSafetyRoute: typeof PublicSafetyRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAuthRoute: PublicAuthRouteWithChildren,
  PublicAboutRoute: PublicAboutRoute,
  PublicAuctionsRoute: PublicAuctionsRouteWithChildren,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicPoliciesRoute: PublicPoliciesRoute,
  PublicSafetyRoute: PublicSafetyRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardMyAuctionsRouteChildren {
  DashboardMyAuctionsIdRoute: typeof DashboardMyAuctionsIdRoute
  DashboardMyAuctionsNewRoute: typeof DashboardMyAuctionsNewRoute
}

const DashboardMyAuctionsRouteChildren: DashboardMyAuctionsRouteChildren = {
  DashboardMyAuctionsIdRoute: DashboardMyAuctionsIdRoute,
  DashboardMyAuctionsNewRoute: DashboardMyAuctionsNewRoute,
}

const DashboardMyAuctionsRouteWithChildren =
  DashboardMyAuctionsRoute._addFileChildren(DashboardMyAuctionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAuctionsRoute: typeof DashboardAuctionsRoute
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardMyAuctionsRoute: typeof DashboardMyAuctionsRouteWithChildren
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPayoutsRoute: typeof DashboardPayoutsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSetupRoute: typeof DashboardSetupRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuctionsRoute: DashboardAuctionsRoute,
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardMyAuctionsRoute: DashboardMyAuctionsRouteWithChildren,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPayoutsRoute: DashboardPayoutsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSetupRoute: DashboardSetupRoute,
  DashboardUsersRoute: DashboardUsersRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
